import type { UserService } from './authService';
import type { ConfigService } from './configService';
import type { LessonService } from './lessonService';
import type { SentenceService } from './sentenceService';
import type { WordService } from './wordService';
import type { UserLessonProgressService } from './userLessonProgressService';
import type { UserScoreService } from './userScoreService';
import type { UserActionLogService } from './userActionLogService';
import type { ChartService } from './chartService';
import type { UserSettingService } from './userSettingService';
import type { CronService } from './cronService';
import type { ObjectStorageService } from './objectStorageService';
import type { TtsService } from './ttsService';
import type { OpenAIService } from './ai/openaiService';
import type { TextProcessingService } from './textProcessingService';
import type { LingQService } from './import/lingqService';
import type { AgentSessionService } from './agentRuntime/agentSessionService';
import { PrismaClient } from '@prisma/client';

export type { DB } from '../db/types';
export { kysely, withKysely } from './kysely';

export type Context = {
  prisma: PrismaClient;
  authService: UserService;
  configService: ConfigService;
  lessonService: LessonService;
  sentenceService: SentenceService;
  wordService: WordService;
  userLessonProgressService: UserLessonProgressService;
  userScoreService: UserScoreService;
  userActionLogService: UserActionLogService;
  chartService: ChartService;
  userSettingService: UserSettingService;
  cronService: CronService;
  objectStorageService: ObjectStorageService;
  ttsService: TtsService;
  openaiService: OpenAIService;
  textProcessingService: TextProcessingService;
  lingqService: LingQService;
  agentSessionService: AgentSessionService;
};
